apiVersion: v1
kind: Service
metadata:
  annotations:
    argo-rollouts.argoproj.io/managed-by-rollouts: canary-demo
  labels:
    app.kubernetes.io/instance: demo
  name: canary-demo-preview
  namespace: test
spec:
  clusterIP: 10.107.224.188
  clusterIPs:
  - 10.107.224.188
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: canary-demo
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
