apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app.kubernetes.io/instance: demo
  name: canary-demo
  namespace: test
spec:
  clusterIP: 10.99.158.251
  clusterIPs:
  - 10.99.158.251
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: canary-demo
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
